services:
  server:
    build:
      context: .
      target: final
    environment:
      - PORT=8085
      - DATABASE_URL=postgres://svc_contact:contact_pwd@db:5432/contacts?timezone=UTC
    ports:
      - 8085:8085
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: contacts
      POSTGRES_PASSWORD: contact_pwd
      POSTGRES_USER: svc_contact
      TZ: UTC
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d contacts  -U svc_contact" ]
      interval: 10s
      timeout: 5s
      retries: 5
