services:
  server:
    build:
      context: .
      target: build
    environment:
      - ENV=ci
      - PORT=8085
      - DATABASE_URL=postgres://svc_contact:contact_pwd@db_test:5432/contacts?timezone=UTC
    depends_on:
      db_test:
        condition: service_healthy
  db_test:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: contacts
      POSTGRES_PASSWORD: contact_pwd
      POSTGRES_USER: svc_contact
      TZ: UTC
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d contacts  -U svc_contact" ]
      interval: 10s
      timeout: 5s
      retries: 5
