name: CI
on:
  push:
    branches:
      - main
env:
  DOCKER_BUILDKIT: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Build
        run: go build .
      - name: Run tests
        run: make unit_test

      - name: Run integration tests
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
        run: make docker-integration-tests

      - name: Run acceptance tests
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
        run: make docker-acceptance-tests

      - name: Docker compose down
        if: always()
        run: docker-compose -f docker-compose.ci.yml down